### ISSUE TITLE
Dovecot still will not run...

### ISSUE THREAD

**Issue by toastedmail** [msimerson/Mail-Toaster-6#87] opened 2016-10-31 20:26 UTC
Not sure why, now rerunning provision vpopmail worked

However rerunning provision dovecot seems to install OK but it won't run..

  ***   dovecot already in /etc/jail.conf   ***

   ***   service jail start dovecot   ***

Starting jails: dovecot.

Success! A new 'dovecot' jail is provisioned

# exit
root@mxbt1:~ # ps auxw |grep dovecot
root     1260   0.0  0.1  18832   2328  0  S+    4:20PM    0:00.00 grep dovecot
root@mxbt1:~ # jailmanage dovecot
Entering jail dovecot
    /sbin/mount_nullfs /usr/ports /jails/dovecot/usr/ports
    /sbin/mount_nullfs /var/cache/pkg /jails/dovecot/var/cache/pkg
[dovecot] Fetching vuln.xml.bz2: 100%  648 KiB 663.2kB/s    00:01    
0 problem(s) in the installed packages found.
[root@dovecot ~]# /usr/local/etc/rc.d/dovecot start
==Error==
Config file /data/etc/dovecot.conf does not exist. If this is
a new installation, please create the config files as outlined in
	# pkg info -D dovecot2
/usr/local/etc/rc.d/dovecot: WARNING: /data/etc/dovecot.conf is not readable.
/usr/local/etc/rc.d/dovecot: WARNING: failed precmd routine for dovecot

The file IS there:

# ls -l /data/etc/
total 1
lrwxr-xr-x  1 root  wheel  30 Oct 31 02:09 dovecot.conf -> /data/dovecot/etc/dovecot.conf

**Comment by msimerson** [comment] 2016-10-31 21:01
duplicate of #85

**Closed by msimerson** 2016-10-31 21:01 UTC
