### ISSUE TITLE
Provision for some jails does not complete

### ISSUE THREAD

**Issue by barontel** [msimerson/Mail-Toaster-6#52] opened 2016-09-03 00:17 UTC
When trying to re-provision Haraka the process doesn;t complete:
.
.
.
   ***   starting haraka   ***

sysrc -R /jails/stage haraka_enable=YES
haraka_enable:  -> YES
haraka_flags:  -> -c /usr/local/haraka
jexec stage service haraka start
loaded TLD files: 1=1490 2=5990 3=2318
loaded 8040 Public Suffixes
loglevel: LOGINFO
Starting up Haraka version 2.8.8
[INFO] [-] [core] Loading plugins
[INFO] [-] [core] Loading plugin: process_title
[INFO] [-] [core] Loading plugin: log.syslog
[INFO] [-] [core] Loading plugin: access
[INFO] [-] [access] skipping helo.checks.regexps
[INFO] [-] [core] Loading plugin: connect.p0f
[INFO] [-] [core] Loading plugin: connect.geoip
[INFO] [-] [connect.geoip] provider maxmind with 6 DBs
[INFO] [-] [core] Loading plugin: connect.fcrdns
[INFO] [-] [core] Loading plugin: dnsbl
[INFO] [-] [core] Loading plugin: helo.checks
[INFO] [-] [core] Loading plugin: tls
[INFO] [-] [core] Loading plugin: auth/auth_vpopmaild
[INFO] [-] [core] Loading plugin: mail_from.is_resolvable
[INFO] [-] [core] Loading plugin: spf
[INFO] [-] [core] Loading plugin: rcpt_to.qmail_deliverable
[INFO] [-] [core] Loading plugin: bounce
[INFO] [-] [core] Loading plugin: data.headers
[INFO] [-] [core] Loading plugin: data.uribl
[INFO] [-] [core] Loading plugin: attachment
[INFO] [-] [core] Loading plugin: clamd
[INFO] [-] [clamd] Loading excludes file
[INFO] [-] [core] Loading plugin: avg
[INFO] [-] [core] Loading plugin: spamassassin
[INFO] [-] [core] Loading plugin: rspamd
[INFO] [-] [core] Loading plugin: dkim_sign
[INFO] [-] [core] Loading plugin: karma
[INFO] [-] [core] Loading plugin: queue/smtp_forward
[INFO] [-] [core] Loading plugin: limit
[INFO] [-] [core] Loading plugin: watch
[INFO] [-] [core] Loading plugin: redis

   ***   waiting for Haraka to start listeners   ***

   ***   testing Haraka   ***

The process stops ^^^^

**Comment by msimerson** [comment] 2016-09-03 04:26
same issue, duplicate of #49

**Closed by msimerson** 2016-09-03 04:26 UTC

**Comment by barontel** [comment] 2016-09-05 14:40
Hi Matt,
I will try upgrading later today. Just one thing. If the upgrade of 
haraka works, are the files in /config still same or must they be 
changed to values in old/config ?

Thanks Matt.

Regards,
+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+
Lanny Baron
BaronTEL

The Future of Business Telephony Services is Here and Now!

Tel: 416.477.5411
Toll-Free: 888.241.8647
Fax: 647.693.9492
+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+
