### ISSUE TITLE
Installed new MT6 using FreeBSD 10.2 can't login imap

### ISSUE THREAD

**Issue by toastedmail** [msimerson/Mail-Toaster-6#93] opened 2016-11-01 12:25 UTC
Created new VM and installed MT6 this time using FreeBSD 10.2 ISO.
Everything but monitor jail installed.

Jailmange vpopmail and ~vpopmail/bin/vuserinfo username@domain.tld works 
# jls
   JID  IP Address      Hostname                      Path
     1  172.16.15.3     dns                           /jails/dns
     2  172.16.15.4     mysql                         /jails/mysql
     4  172.16.15.15    dovecot                       /jails/dovecot
     5  172.16.15.10    webmail                       /jails/webmail
     6  172.16.15.12    haproxy                       /jails/haproxy
     7  172.16.15.5     clamav                        /jails/clamav
     8  172.16.15.14    avg                           /jails/avg
     9  172.16.15.16    redis                         /jails/redis
    10  172.16.15.13    rspamd                        /jails/rspamd
    11  172.16.15.17    geoip                         /jails/geoip
    12  172.16.15.6     spamassassin                  /jails/spamassassin
    13  172.16.15.9     haraka                        /jails/haraka
    15  172.16.15.8     vpopmail                      /jails/vpopmail

**Problem is no one can login**:

Nov  1 08:20:26 dovecot dovecot: imap-login: Disconnected (auth failed, 1 attempts in 17 secs): user=<lanny@domain.tld>, method=CRAM-MD5, rip=xx.xxx.xx.xx, lip=172.16.15.15, TLS, session=<athyWDxALvpj7UjS> 

What has to be fixed?

**Comment by toastedmail** [comment] 2016-11-01 12:40
Added password debub in dovecot/local.conf
Seeing: 

Nov  1 08:38:09 dovecot dovecot: auth-worker(19031): vpopmail(lanny@domain.tld,99.237.72.210,<v57TmDxAmPpj7UjS>): unknown user

**Comment by toastedmail** [comment] 2016-11-01 13:43
Notice that any re-provisioning seems to mess up vpopmail as in, ~vpopmail/bin/vuserinfo user@domain.tld unknown user or no such user.
Wondering when re-provisioning vpopmail it displays
[ERROR] Fetching of 'ftp://ftp.cpan.org/pub/CPAN/authors/01mailrc.txt.gz' failed: Command failed: fetch: ftp://ftp.cpan.org/pub/CPAN/authors/01mailrc.txt.gz: Can't open data connection

**Comment by toastedmail** [comment] 2016-11-01 14:34
Re-provisioned vpopmail. #jailmanage vpopmail
# ~vpopmail/bin/vuserinfo  -D cybertouch.org
ame:   postmaster
passwd: $1$qVrFM35d$Kw/lgjF/ZFL5ftQntZ1hX/
clear passwd: xxXXxxXXxxxXXX
comment/gecos: Postmaster
uid:    0
gid:    0
flags:  0
gecos: Postmaster
limits: No user limits set.
dir:       /usr/local/vpopmail/domains/cybertouch.org/postmaster
quota:     NOQUOTA
usage:     NOQUOTA
account created: Tue Aug 25 08:48:50 2015
last auth: Never logged in


Please tell me what the issue is and how to fix it.

**Comment by toastedmail** [comment] 2016-11-01 14:44
Provsion dovecot is very different from the sample output page for it. 

Prior to re-provision dovecot, #manage vpopmail

# ~vpopmail/bin/vuserinfo lanny@baron.cc
name:   lanny
passwd: $1$SsHhV0Vt$8vd3Up7ixZeUwOPhKwUKv.
clear passwd: abc123
comment/gecos: lanny
uid:    0
gid:    0
flags:  0
gecos: lanny
limits: No user limits set.
dir:       /usr/local/vpopmail/domains/baron.cc/lanny
quota:     NOQUOTA
usage:     NOQUOTA
last auth: Mon Oct 31 00:26:59 2016
last auth ip: imap

Just re-provisioned dovecot now and then in vpopmail jail ran:
[root@vpopmail ~]# ~vpopmail/bin/vuserinfo lanny@baron.cc
no such user lanny@baron.cc

**Comment by toastedmail** [comment] 2016-11-01 15:02
When mentioning output of provision dovecot is completely different than sample output page on github, for one thing, the following doesn't show up at all:

 +----------------------------- dovecot2-2.2.21 --------------------------------+        
     | +--------------------------------------------------------------------------+ |        
     | |+[x] DOCS            Build and/or install documentation                   | |        
     | | [x] EXAMPLES        Build and/or install examples                        | |        
     | |+[x] KQUEUE          kqueue(2) support                                    | |        
     | | [x] LIBWRAP         TCP wrapper support                                  | |        
     | |+[ ] LZ4             LZ4 compression support                              | |        
     | |+[x] SSL             SSL protocol support                                 | |        
     | | [x] VPOPMAIL        vpopmail support                                     | |        
     | |----------------------------- Database support ---------------------------| |        
     | |+[ ] CDB             CDB database support                                 | |        
     | |+[ ] LDAP            LDAP protocol support                                | |        
     | |+[ ] MYSQL           MySQL database support                               | |        
     | |+[ ] PGSQL           PostgreSQL database support                          | |        
     | |+[ ] SQLITE          SQLite database support                              | |        
     | |------------------------- Full text search plugins -----------------------| |        
     | |+[ ] ICU             Use libicu for FTS unicode normalization             | |        
     | |+[ ] LUCENE          CLucene FTS support                                  | |        
     | |+[ ] SOLR            Solr FTS support                                     | |        
     | |+[ ] TEXTCAT         Libtextcat FTS support                               | |        
     | |----------------------- GSSAPI Security API support ----------------------| |        
     | |+(*) GSSAPI_NONE     Build without GSSAPI support                         | |        
     | |+( ) GSSAPI_BASE     Use GSSAPI from base                                 | |        
     | |+( ) GSSAPI_HEIMDAL  Use Heimdal GSSAPI from security/heimdal             | |        
     | |+( ) GSSAPI_MIT      Use MIT GSSAPI from security/krb5                    | |        
     | +--------------------------------------------------------------------------+ |        
     +------------------------------------------------------------------------------+        
     |                       <  OK  >            <Cancel>                           |        
+------------------------------------------------------------------------------+

**Comment by msimerson** [comment] 2016-11-01 17:54
duplicate of #85

**Closed by msimerson** 2016-11-01 17:54 UTC
